### PR TITLE
moved content from index layout

### PR DESCRIPTION
**Pull request by calcnerd256**
The index.md file is a markdown file that references the index.html layout.
Since markdown is a superset of HTML, there should be no problem with moving HTML content into a markdown file.
This commit blindly moves some of the HTML content from the index.html layout template file into the index.md markdown file.
Before approving it, feel free to check that every line merely moved and did not otherwise change during this commit, as this is my intent.
I also removed the old content that does not appear in the final rendering.  That is, the line about having no idea.

### CODE REVIEW

**Review by mbeasley32 — COMMENTED** [review]
I think I understand the logic if this change, but I'm not sure why you want to make it. Is it the jekyll way to have all the html in the corresponding html file and have the markdown files with the bare minimum to reference that html? Or does it matter?

**Comment by calcnerd256** [comment]
> I think I understand the logic if this change, but I'm not sure why you want to make it. Is it the jekyll way to have all the html in the corresponding html file and have the markdown files with the bare minimum to reference that html? Or does it matter?

After a few more changes like this, we can remove redundancy among the layout files and reuse a few (or even a single) layout file(s).
In another branch, I've gone way overboard with that idea and moved most of the content into structured yaml or whatever the config file is made of.  As I backport  those changes one-by-one, we can find where you draw the line on that and say, "Now, this is too much."

**Comment by mbeasley32** [comment]
I believe it won't blow everything up to make these consolidations, but just to be sure... Did you test it on a local server and make sure everything loads correctly?

**Comment by calcnerd256** [comment]
> I believe it won't blow everything up to make these consolidations, but just to be sure... Did you test it on a local server and make sure everything loads correctly?

Lemme go do that for this change and then get back to you.
I checked everything in the history of my gh-pages branch, but this isn't that, so I need to check this, too.
Good catch; sorry for being sloppy.

**Comment by calcnerd256** [comment]
> > I believe it won't blow everything up to make these consolidations, but just to be sure... Did you test it on a local server and make sure everything loads correctly?
> 
> Lemme go do that for this change and then get back to you.
> I checked everything in the history of my gh-pages branch, but this isn't that, so I need to check this, too.
> Good catch; sorry for being sloppy.

Glad you had me check.  It looks like I was completely wrong about being able to simply drop the HTML into a markdown file.  I'll push another commit here that renames it to have a .html file extension and see if that's all it needs or not.

**Comment by calcnerd256** [comment]
> Glad you had me check. It looks like I was completely wrong about being able to simply drop the HTML into a markdown file. I'll push another commit here that renames it to have a .html file extension and see if that's all it needs or not.

Alright, that seems to work on my end.

**Comment by calcnerd256** [comment]
> Good catch; sorry for being sloppy.

Funny thing is, I think I made this same mistake when I was first making these changes last year.  In the intervening time, I managed to forget the lesson I'd learned from it.  Maybe it'll stick better this time.  It probably won't.

**Comment by mbeasley32** [comment]
> > Glad you had me check. It looks like I was completely wrong about being able to simply drop the HTML into a markdown file. I'll push another commit here that renames it to have a .html file extension and see if that's all it needs or not.
> 
> Alright, that seems to work on my end.

So at this point does that mean you essentially moved the index.md contnent into the index.html file?

**Comment by calcnerd256** [comment]
> So at this point does that mean you essentially moved the index.md contnent into the index.html file?

Yes.  I moved most of /_layouts/index.html into /index.html in the hopes of later consolidating the various layout files.

**Comment by calcnerd256** [comment]
> I think I understand the logic if this change, but I'm not sure why you want to make it. Is it the jekyll way to have all the html in the corresponding html file and have the markdown files with the bare minimum to reference that html? Or does it matter?

It seems to me, based on the names of things, that the Jekyll way of doing things would be to have the content in these top-level files that are currently markdown (whether or not they remain markdown) and to have reusable HTML templates in the _layouts directory.

**Comment by calcnerd256** [comment]
I'm not sure whether Jekyll needs us to specify `permalink:` for `/index.html`, but I've added it just in case.  I hope it doesn't need it, and I doubt there's any harm in having it.

**Review by mbeasley32 — APPROVED** [review]

**Review by mbeasley32 — APPROVED** [review]

**Pull request merged**
