### PR TITLE
Whitespace

### PR DESCRIPTION
**Pull request by calcnerd256**
Additional whitespace changes.
This one is a little more advanced than #1 was.
It contains some changes that are like that one, but it also contains some hacking about with the 'comment' template tags and with some other template tags, so as to suppress some whitespace in the HTML that the templates generate.

### CODE REVIEW

**Comment by calcnerd256** [comment]
I'm not sure why I've omitted 0a10b0c2c414925a22d5ba4838704d8294fe60eb from this pull request.  I guess I'll need to look at the generated site after this merge and see if that commit is needed.

**Review by mbeasley32 — APPROVED** [review]
Looks good. Question: What is the main driver for eliminating whitespace? Is it efficiency related? Code cleanliness? Best stylistic practice? All or none of the above? Just curious. Thanks!

**Comment by calcnerd256** [comment]
> Question: What is the main driver for eliminating whitespace? Is it efficiency related? Code cleanliness? Best stylistic practice? All or none of the above?

It is purely aesthetic.
I'm not trying to get rid of all whitespace; I'm trying to make the whitespace consistent.
There is a difficult balance between how the template code appears in my editor and how the generated markup appears if I view the web page's HTML source.
For more details on the journey of my struggle with this balance (and with learning the specifics of this template language), see the commits in my branch that has the whole history here: https://github.com/calcnerd256/hope-community.github.io/commits/whitespace-history

**Comment by calcnerd256** [comment]
> > Question: What is the main driver for eliminating whitespace? Is it efficiency related? Code cleanliness? Best stylistic practice? All or none of the above?
> 
> It is purely aesthetic.

I say that, but there's a pride thing, too: I want to be able to be proud to have worked on this website.  I don't want to cut corners just to make something work (though I find I have to, sometimes; still I'd prefer to minimize it).
I've heard it said that Amish craftsmen make really good chairs, and I've heard it said that they put a lot of attention to detail into the underside of the chair, even though nobody looks there.  I've heard it claimed that the rationale is that God sees it.  I don't know how much of this narrative actually holds for any actual Amish person, but it's a narrative I've heard, and it makes a decent metaphor for caring about the generated HTML source.
I, personally, also sometimes look at the source of websites I visit.  I judge their authors by what I find there, and I can sometimes guess how the page was generated or what shortcuts were taken by looking at such things as the whitespace of the generated output.  This standard to which I hold others, I seek to live up to it, myself.
I hope I don't regret getting this personal in public at some point in the future.

**Comment by calcnerd256** [comment]
> I'm not sure why I've omitted [0a10b0c](https://github.com/Hope-Community/hope-community.github.io/commit/0a10b0c2c414925a22d5ba4838704d8294fe60eb) from this pull request. I guess I'll need to look at the generated site after this merge and see if that commit is needed.

Looks like we do want that commit.  I'll make another tiny pull request for it.
Sorry for not including it in this pull request.

**Pull request merged**
